on:
  push:
    branches:
      - correction

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
          cache: 'maven'
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml